[이지우] 과제 제출합니다
Bamdoliro/bamdol_publishing_test pull request #1
Opened 2023-07-18 05:59 UTC by E-jiwoo

## 📄 Summary

> 마루 홈페이지의 메인 화면 디자인을 html과 css로 구현해보았다

<br>

## 🔨 Tasks

- HTML
- CSS

<br>

## 🙋🏻 More
- <보완해야할 점>
  회색 사각형을 사진 크기에 맞게 완벽하게 덮지 않고 전체적으로 덮은 것이 보완해야 할 점인 것 같다

2023-07-18 06:44 UTC, SEOKKAMONI requested changes
과제하느라 수고하셨습니다 끝까지 포기하지않고 구현해온 부분이 너무 대견스럽네요

리뷰를 천천히 읽어보면서 코드를 수정하시면 될 것 같습니다 !

추가적으로 이제부터 개발하는 관점을 조금 바꾸시면 좋을것같아요
그냥 개발해서 구현한다 보다는 그 후 개발자가 좀 더 보기 좋게 아무나 와도 무슨 코드인지 읽기 쉽게 만든다를 생각하면서 코딩하다 보시면 더 좋은 개발자가 될 것 같아요 !

2023-07-18 06:44 UTC, SEOKKAMONI commented on styles/text.css
> +}
지금 이 두개의 스타일은 text라기 보다는 text box에 가까운것같아요 text를 감싸는 box에 주는 css인것같거든요

제 생각에는 만약 웹사이트가 커져 text, tex2 코드가 재활용될것을 고려해서 text box가 아닌 온전히 text css만 넣으면 좋을것같아요 
text코드를 가지고 예제를 보여드릴게요 !

온전히 text만 남겨둔 후

```css
.text{
    line-height: 93.6px;
    font-family: Pretendard,'Noto Sans KR', sans-serif;
    font-weight: 700;
    font-size: 72px;
    letter-spacing: -1.5px;
    color: #ffffff;
}
```

```html
 <div>
    <p class="text">꿈을 향한 도전,</p>
    <p class="text">미래를 여는 학교</p>
 </div>
```

이런식으로 한다면 나중에 text를 재활용 할 수 있겠죠?

추가적으로 text의 font style은 같을수있지만 색깔은 여러 색으로 바뀔수있어요 !

```css
.black {
   color: black;
}

.red {
  color: red;
}
```
이런식으로 색깔을 정의 한 후

```html
 <div>
    <p class="text red">꿈을 향한 도전,</p> // 빨강
    <p class="text black">미래를 여는 학교</p> // 검정
 </div>
```

class의 특성을 사용하여 이런식으로 사용한다면 유동적으로 색깔도 변경 할 수 있게되어

더 좋은 코드가 될것같아요 !

2023-07-18 06:44 UTC, SEOKKAMONI commented on styles/button.css
> +  float: left;
정렬에서의 float은 별로 좋지않아요 display flex를 사용해보는것을 고려해봐도 좋을것같아요

<img width="790" alt="image" src="https://github.com/Bamdoliro/bamdol_publishing_test/assets/102217654/22d712c8-fca8-404f-8c8f-7b49e3ba7319">

2023-07-18 06:44 UTC, SEOKKAMONI commented on styles/style.css
> +}
지금은 img가 하나 뿐이여서 잘 작동할지 몰라도 나중에 img 태그가 여러개가 되었을때는 문제가 발생할것같아요 !

background-img와 같이 class나 id를 주어 스타일을 먹인다면 추후 문제를 예방 할 수 있을것같아요

2023-07-18 06:44 UTC, SEOKKAMONI commented on styles/style.css
> +}
background에 이미지를 넣을때는 background-image와 같은 css 속성도 있으니 고려해보시면 좋을것같습니다 ~

https://www.codingfactory.net/10590

2023-07-18 06:44 UTC, SEOKKAMONI commented on index.html
> +                    <div class="square"></div>
안에 아무 요소도 없다면
```suggestion
                    <div class="square" />
```

이런식으로 쓰는것은 어떨까요?

2023-07-18 06:44 UTC, SEOKKAMONI commented on index.html
> +            <img src="img/bssm.png"style="width:100%;">
```suggestion
            <img src="img/bssm.png" style="width:100%;">
```

띄어쓰기 !

2023-07-18 06:44 UTC, SEOKKAMONI commented on index.html
> +                        <button id="receipt">원서 접수 시작하기<img class="arrow" src="img/arrow.png"></button>
네이밍 관련 질문입니다 !

receipt는 여러가지 의미가 있어 유지보수 입장에서 코드를 처음 봤을때 해석하기 힘들것같아요 !
원서 접수 시작하기니깐 start-button과 같이 명시적인 네이밍은 어떨까요?

따로 receipt를 사용 한 이유를 듣고싶어요

2023-07-18 06:44 UTC, SEOKKAMONI commented on index.html
> +                    </div>
시작하기 button은 div태그로 감싸지않고도 button태그 하나만으로도 만들 수 있을것같아요 !

button 태그 하나 만으로 만들어보는건 어떨까요?

2023-07-18 06:44 UTC, SEOKKAMONI commented on index.html
> +    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />
너무 잘 나누어주셨습니다 !

하지만 조금 아쉬운 부분이 보이는데요 style css안에는 현재 main, header부분에 css가 같이 있는것같아요

header와 main도 css 파일을 나눠준다면 유지보수 입장에서 상당히 편할것같아요 !

2023-07-18 06:44 UTC, SEOKKAMONI commented on styles/button.css
> +  padding-left: 1200px;
유동적인 사이트를 만드려면 극단적인 padding-left: 1200px;은 좋지 않습니다 !

header부분을 display flex를 공부하시고 다시 만들어보시는걸 추천드려요!

https://www.youtube.com/watch?v=7neASrWEFEM

2023-07-18 06:44 UTC, SEOKKAMONI commented on styles/button.css
> +  padding-left: 10px;
icon을 png로 저장하는것이 아닌 svg로 저장한다면 svg파일안에 style이 정의되어있어 style를 따로 정의하지 않아도 됩니다 ! 
저런 아이콘들은 svg로 저장하여 다시 퍼블리싱을 해보는것은 어떨까요?

2023-07-18 06:44 UTC, SEOKKAMONI commented on styles/style.css
> +}
이러한 초기 css는 reset css에 정의해주세요 !

2023-07-18 06:44 UTC, SEOKKAMONI commented on styles/style.css
> +}
회색 배경 또한 이런식으로 하는것이 아닌 background-filter가 있습니다 !

그리고 애초에.. 사진 다운로드를 블러 처리되어있는 사진을 다운로드했다면 이렇게 정의해주는 일이 없어졌을것같습니다 !

신준서 디자이너에게 연락해보세요 !
디자이너와 소통하는것도 실력입니당

2023-07-18 06:44 UTC, SEOKKAMONI commented on styles/style.css
> +  left: 110px;
마찬가지로 flex를 사용했었다면 좀 더 좋은 코드로 처리할 수 있었을 것 같아요

2023-07-18 06:44 UTC, SEOKKAMONI commented on styles/style.css
> +  line-height: 23.4px;
font 속성은  class로 따로 뺴서 사용해보는것은 어떨까요?

2023-07-18 06:49 UTC, arkk200 requested changes

2023-07-18 06:49 UTC, arkk200 commented on styles/text.css
> +}
텍스트 별로 클래스를 나눈 점이 보기 좋네요👍

2023-07-18 06:49 UTC, arkk200 commented on styles/style.css
> +  float: left;
`li` 태그에 `float` 속성보단 부모 태그인 `ul` 태그에 `display: flex` 속성을 주는게 좋아요.
`display: flex` 속성은 float 속성보다 젊어서 레이아웃을 구성하는데 다양하고 많은 기능을 제공하고 있어요.
그리고 [이 사이트](https://caniuse.com/?search=flex)에서 보면 대부분의 브라우저가 `display: flex` 속성을 지원하고 있기 때문에 적극적으로 활용하는게 좋아요!
전 css flex 속성에 대한 내용은 [이 사이트](https://studiomeal.com/archives/197) 에서 학습했어요

2023-07-18 06:49 UTC, arkk200 commented on index.html
> +                <div id="top">
header나 section, nav같은 시멘틱 태그를 사용하는게 좋아요! 시멘틱 태그의 장점은 검색 엔진이 최적화되어 사이트가 상단에 노출되기 쉬워져요. [w3schools](https://www.w3schools.com/html/html5_semantic_elements.asp) 사이트에서 자세한 내용을 알 수 있습니다

2023-07-18 06:49 UTC, arkk200 commented on index.html
> +                    <div class="square"></div>
이 태그를 추가한 이유가 무엇인가요...?

2023-07-18 06:49 UTC, arkk200 commented on index.html
> +            </div>
닫는 div 태그가 하나 더 들어가있네요 ㅋㅋ

2023-07-18 06:49 UTC, arkk200 commented on index.html
> +            <img src="img/bssm.png"style="width:100%;">
접근성을 위해, 그리고 seo를 위해서 img태그에 alt 속성을 추가해주는 것이 좋아요!

2023-07-18 06:50 UTC, E-jiwoo commented on index.html
> +                        <button id="receipt">원서 접수 시작하기<img class="arrow" src="img/arrow.png"></button>
원서 접수에서 접수를 영어로 해서 receipt라고 했었습니다

2023-07-18 11:22 UTC, E-jiwoo commented
수정하였습니다!

2023-07-19 15:13 UTC, qodldks commented
아 개웃경 수고하셧어요

2023-07-19 15:13 UTC, SEOKKAMONI reviewed
수고하셨어요 엄청 깔끔하네요 !!

2023-07-19 15:13 UTC, SEOKKAMONI commented on styles/button.css
> +}
button 정렬을 relative와 absolute를 사용하신것같아요 !
정렬을 할때는 postition보단 flex를 활용하시면 더 좋은 코드가 될것같아요!

2023-07-19 15:13 UTC, SEOKKAMONI commented on styles/style.css
> +}
html 전체에 박으면 나중에 페이지가 추가될때 다른 페이지도 오염되버려요

class="container"나 main에 주는것이 적절해보여요!

2023-07-19 15:27 UTC, arkk200 requested changes

2023-07-19 15:27 UTC, arkk200 commented on index.html
>          <div class="container">
https://dev.to/kazmi066/choosing-the-right-css-naming-convention-for-your-project-3kj6
css 네이밍 컨벤션에 대한 내용이예요
참고하시면 좋을 것 같습니다

2023-07-19 15:27 UTC, arkk200 commented on styles/header.css
> +    padding-left: 100px;
좌우로 같은 간격으로 떨어져 중앙으로 정렬되어 있는 레이아웃은 마진또는 패딩을 양쪽 다 주는게 좋을 것 같아요
<img width="695" alt="스크린샷 2023-07-20 오전 12 09 44" src="https://github.com/Bamdoliro/bamdol_publishing_test/assets/102217839/d13d016c-6c82-435b-a147-fb5f691f9fb2">
`#top`이 적용된 레이아웃 같은 경우 양쪽이 같은 간격으로 띄워져 있으니 `padding-left: 100px;`만 주기보단 `padding: 0 100px;`로 양쪽에 똑같은 간격을 주는게 좋을 것 같아요
이렇게 하는게 좀 더 깔끔한 UI를 만들 수 있다고 생각합니다!

2023-07-19 15:27 UTC, arkk200 commented on styles/header.css
> +    padding-left: 100px;
다른 것들도 마찬가지예요

2023-07-24 05:12 UTC, SEOKKAMONI approved these changes
수고하셨습니다~

2023-07-26 08:43 UTC, arkk200 approved these changes
과제한다고 수고 많으셧습니다

2025-04-19 16:41 UTC, closed without merging