Seonghoon
Bamdoliro/bamdol_publishing_test pull request #2
Opened 2023-07-18 06:10 UTC by seonghoon07

## 📄 Summary

>

<br>

## 🔨 Tasks

- 

<br>

## 🙋🏻 More
<img width="1440" alt="스크린샷 2023-07-18 오후 3 09 50" src="https://github.com/Bamdoliro/bamdol_publishing_test/assets/119480957/e7f117c5-ba0c-4f2c-929f-2b47a93121b6">

2023-07-18 07:03 UTC, arkk200 requested changes

2023-07-18 07:03 UTC, arkk200 commented on index.html
> +                <div class="nav">
여기 nav 시멘틱 태그 쓰는게 좋아보여요

2023-07-18 07:03 UTC, arkk200 commented on styles/mainText/mainText.css
> +  line-height: 130%;
피그마를 보면 원서 접수 시작하기 글자의 스타일과 네비에기션에 버튼 글자의 스타일이 동일한 것을 알 수 있어요.
\#title과 \#sub-title 처럼 스타일에 따라 분리한 거처럼 클래스로 따로 빼서 태그에 적용하는게 괜찮아 보이는데 어떠신가요?

2023-07-18 07:03 UTC, SEOKKAMONI requested changes
아픈 팔 붙잡고 구현하느라 수고하셨습니다 !

기본적으로 flex에 대한 이해도가 있는것같아 보기좋아요 !

하지만 코드에서 피그마에 너무 의존하여 그대로 복붙한 부분도 있는것같아 보여요
피그마에 있는 코드를 의존하기보단 참고용으로 사용하는것이 좋습니다 !

해당 코드 수정 후 다시 리뷰를 요청해주세요 !!! 정말 고생 많으셨어요 !

2023-07-18 07:03 UTC, SEOKKAMONI commented on index.html
> +                            <img src="./imgs/arrow_forward.svg" alt="화살표"/>
```suggestion
                            <img src="./imgs/arrow_forward.svg" alt="arrow-icon"/>
```

한국어보단 영어가 더 좋을것같아요 !

2023-07-18 07:03 UTC, SEOKKAMONI commented on index.html
> +                </button>
버튼 하나 만드는데 너무 많은 태그를 사용하신것같아요
버튼은 Button tag 하나로도 충분히 구현하실수있습니다 ! 

다시 구현해보는것은 어떨까요?

2023-07-18 07:03 UTC, SEOKKAMONI commented on index.html
> +    <link href="./styles/mainText/mainText.css" rel="stylesheet" type="text/css" />
```suggestion
    <link href="./styles/texts/mainText.css" rel="stylesheet" type="text/css" />
```

다음과 같이 texts폴더에 mainText 파일을 하는것은 어떨까요?

2023-07-18 07:03 UTC, SEOKKAMONI commented on index.html
> +    <link href="./styles/header/bottom-header.css" rel="stylesheet" type="text/css" />
잘 분리하셨습니다 !

나중에 분리할때는 네이밍에 좀 더 신경써주세요 !

2023-07-18 07:03 UTC, SEOKKAMONI commented on index.html
> +                    </button>
스타일이 따로 안들어가는것같은데 id를 붙인 이유가 따로 있나요?

2023-07-18 07:03 UTC, SEOKKAMONI commented on styles/header/bottom-header.css
> +  line-height: 130%;
따로 text 폴더에 css를 빼서 class를 사용하여 해당 font가 적용된 태그들에게 주는 방식은 어떨까요?

2023-07-18 07:03 UTC, SEOKKAMONI commented on styles/header/top-header.css
> +}
absolute가 따로 있는 이유가 있나요? 이유가 궁금해요 !

2023-07-18 07:03 UTC, SEOKKAMONI commented on styles/header/top-header.css
> +  padding: 0px 100px;
크 깔끔합니다

2023-07-18 07:03 UTC, SEOKKAMONI commented on styles/mainText/mainText.css
> +  flex-direction: row;
flex에 row는 default값이기 때문에 따로 안넣어주셔두될것같습니다 ~

2023-07-18 07:03 UTC, SEOKKAMONI commented on styles/mainText/mainText.css
> +  margin: 0;
따로 넣어준 이유가 있나여?

2023-07-18 07:03 UTC, SEOKKAMONI commented on styles/header/bottom-header.css
> +  align-self: stretch;
제 생각에는 
```suggestion
  display: flex;
  align-items: center;
  height: 54px;
  padding: 0px 101px;
```

이렇게만 해도 되지않나요?

저렇게 코드를 짠 이유가 있을까요?

2023-07-19 13:25 UTC, seonghoon07 commented on index.html
> +                <div class="nav">
수정하였습니다

2023-07-19 13:30 UTC, seonghoon07 commented on styles/mainText/mainText.css
> +  line-height: 130%;
좋은 것 같습니다! 수정하였습니다

2023-07-19 13:33 UTC, seonghoon07 commented on index.html
> +                            <img src="./imgs/arrow_forward.svg" alt="화살표"/>
수정했습니당

2023-07-19 13:34 UTC, seonghoon07 commented on index.html
> +    <link href="./styles/mainText/mainText.css" rel="stylesheet" type="text/css" />
넵 수정하였습니다

2023-07-19 13:35 UTC, seonghoon07 commented on index.html
> +    <link href="./styles/header/bottom-header.css" rel="stylesheet" type="text/css" />
넵.. 네이밍이 제일 어려운 것 같습니다. 혹시 네이밍을 잘하는 팁 같은게 있을까요??

2023-07-19 13:36 UTC, seonghoon07 commented on index.html
> +                    </button>
아..쓰려고 했다가 코드 효율성이 떨어져 삭제하지 않은 것 같습니다. 수정하였습니다 ㅎㅎ

2023-07-19 13:39 UTC, seonghoon07 commented on styles/header/top-header.css
> +}
absolute를 사용하지 않으면 레이아웃이 화면 전체로 잡히지 않고 header div 밑에 잡혀서 화면 중앙에 Texts를 위치시키기 위해 header에 absolute를 주었습니당. absolute를 주게되면 레이아웃 div가 화면 전체로 잡히게 됩니당 !

2023-07-19 13:39 UTC, seonghoon07 commented on styles/header/top-header.css
> +  padding: 0px 100px;
감자합니당

2023-07-19 13:39 UTC, seonghoon07 commented on styles/mainText/mainText.css
> +  flex-direction: row;
넵 수정하였습니다

2023-07-19 13:43 UTC, seonghoon07 commented on styles/mainText/mainText.css
> +  margin: 0;
레이아웃 말씀하시는 건가용? 자세하게 말해주시몀 감사하겠습니다...

2023-07-19 13:45 UTC, seonghoon07 commented on styles/header/bottom-header.css
> +  align-self: stretch;
이유는 없습니당.. 피그마를 많이 참고해서.. 생각해보니 필요없을 거 같네요!! 수정하였습니당

2023-07-19 13:54 UTC, seonghoon07 commented on index.html
> +                </button>
코드를 더 간단하게 바꾸엇습니다.. 하지만 아래 사진처럼 상하 중앙정렬 이슈가 있습니다. 한번 봐주실 수 있으신가요?

![image](https://github.com/Bamdoliro/bamdol_publishing_test/assets/119480957/170cb83e-b809-4fcf-919e-56c9a42ee69e)

2023-07-19 13:59 UTC, arkk200 commented on styles/mainText/mainText.css
> +  margin: 0;
margin: 0; 속성을 말한 것 같습니다!

2023-07-19 14:34 UTC, arkk200 requested changes

2023-07-19 14:34 UTC, arkk200 commented on styles/Texts/mainText.css
> +.mainText-layout {
이 파일의 이름을 보면 대충 글자 스타일과 관련된 css가 저장될 거라고 생각할 것 같아요
그런데 파일을 뜯어보면 파일 이름과 어울리지 못하는 속성들이 있어 헷갈릴거라고 생각하는데 어떻게 생각하시나요?

2023-07-19 14:34 UTC, arkk200 commented on index.html
> +            <div class="top-header">
https://dev.to/kazmi066/choosing-the-right-css-naming-convention-for-your-project-3kj6
css 네이밍 컨벤션에 대한 내용이예요
참고해보시는 것도 나쁘지 않을 것 같아요!

2023-07-19 14:36 UTC, arkk200 commented
근데 CSS 전체적으로 잘 짜시네요 ㅋㅋ

2023-07-19 14:38 UTC, SEOKKAMONI commented on styles/mainText/mainText.css
> +  margin: 0;
margin 맞습니다 헉.. 자세한 설명을 안적었군요 죄송합니다 !

2023-07-19 14:39 UTC, SEOKKAMONI commented on index.html
> +    <link href="./styles/header/bottom-header.css" rel="stylesheet" type="text/css" />
팁은.. 음 저는 우선 남의 코드를 보고 남이 어떤식으로 네이밍 했는지를 봅니다 그리고 추가적으로 남의 코드가 없다면 구글에 검색해보고 마지막으로 chatgpt한테 물어봅니다! 저는 네이밍에 신경을 많이 써서..

2023-07-19 14:54 UTC, SEOKKAMONI reviewed
많이 좋아지셨네요 ! 

다만 아쉬운점은 styles > Texts, header 폴더 두가지가있는데 앞글자를 대문자로 할건지 소문자로 할건지
공통되게 가져가면 더 좋을것같아요 !

2023-07-19 14:54 UTC, SEOKKAMONI commented on styles/Texts/mainText.css
> +}
text부분만 들어가있어야하는 파일에 button style이 들어가있는것같아요 ! button을 위한 파일에 따로 정의해두는것이 좋겠네요

2023-07-19 14:54 UTC, SEOKKAMONI commented on styles/Texts/mainText.css
> +  margin: 0;
```suggestion
```

넣어주신 이유가 있나요?

2023-07-19 15:04 UTC, SEOKKAMONI commented on index.html
> +                </button>
음 제가 확인해보았는데 원인을 못찾아서 다시 짯는데 잘되는것같습니다

```css
font-family: "Pretendard Variable";
font-weight: 600;
font-size: 18px;
line-height: 130%;
letter-spacing: 0px;
display: flex;
align-items: center;
justify-content: center;
border-radius: 6px;
cursor: pointer;
gap: 10px;
padding: 0px 20px 0px 22px;
background-color: rgb(20, 112, 255);
color: rgb(255, 255, 255);
height: 54px;
```

이건 제가 짠 코드인데요 한번 원인을 찾으면 톡으로 말씀드릴게요 !

2023-07-19 15:26 UTC, SEOKKAMONI commented on index.html
> +                </button>
```css
font-family: "Pretendard Variable";
```
폰트 문제였던걸루~

2023-07-19 15:29 UTC, SEOKKAMONI commented on styles/header/top-header.css
> +}
오홍 그런 이유가 굿굿!~~~

2023-07-20 14:23 UTC, seonghoon07 commented on index.html
> +    <link href="./styles/header/bottom-header.css" rel="stylesheet" type="text/css" />
넵..!

2023-07-20 14:25 UTC, seonghoon07 commented on styles/mainText/mainText.css
> +  margin: 0;
아..딱히 없는 것 같습니다 ㅎㅎ..

2023-07-20 14:26 UTC, seonghoon07 commented on styles/Texts/mainText.css
> +.mainText-layout {
음.. 그럴 수 있을 것 같습니다. 네이밍 관련해서는 공부를 더 해보겠습니다!

2023-07-20 14:27 UTC, seonghoon07 commented on index.html
> +            <div class="top-header">
넵!

2023-07-20 14:27 UTC, seonghoon07 commented on styles/Texts/mainText.css
> +}
넵..

2023-07-20 14:29 UTC, seonghoon07 commented on styles/Texts/mainText.css
> +  margin: 0;
아니요 혹시나 마진이 붙어있을까봐 그런 것 같습니다 수정하였습니다!

2023-07-24 05:13 UTC, SEOKKAMONI approved these changes
수고하셨습니다~

2023-07-26 08:42 UTC, arkk200 approved these changes
바빠서 깜빡잊고 있었네요 ㅎㅎ 수고하셨습니다

2024-06-12 15:11 UTC, closed without merging